app:
  name: "pop-go"
  version: "0.0.1"
  lang: "ru" # en, ru
  temp_folder: ""

log:
  level: "debug" # debug, info, warn, error
  type: "text" # text, json

obfuscator:
  target_path: "../FQW" # absolute or relative path to directory with go.mod
  seed: 0 # 0 to random seed
  comments: true # true, false
  literals:
    level: "easy" # none, easy, medium, hard

builder:
  flags:
    - "-ldflags"
    - "-s -w"
    - "-trimpath"
  goos: "windows"
  goarch: "amd64"
  output_path: "/home/zefixed/Documents/golang/pop-go" # absolute